import random
import string



def get_random_string(length):
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str


def generate_random_name():
    first = ("Ali", "Usama", "Abdullah", "Tariq", "Fatima", "Haris", "Faizan", "Anas", "Farhan", "Abid", "Fahad", "Suleman", "Haseeb",
    "Tayyab", "Saleeem", "Azeem", "Arsal", "Razaq", "Shan", "Ahmed", "Tuseef")
    second = ("Tufeeq", "Asif", "Afridi", "Khan", "Hasnat", "Zahoor", "Utba", "Rasheed", "Ashfaq", "Yaqoob", "Rehmat", "Inayat",
    "Sami", "Zeeshan", "Ajmal", "Javed", "Kamal", "Khalid", "Aziz")
    firrst = random.choice(first)
    seccond = random.choice(second)
    name = (firrst + " " + seccond)
    return name


def generate_random_first_name():
    first = ("Ali", "Usama", "Abdullah", "Tariq", "Fatima", "Haris", "Faizan", "Anas", "Farhan", "Abid", "Fahad", "Suleman", "Haseeb",
    "Tayyab", "Saleeem", "Azeem", "Arsal", "Razaq", "Shan", "Ahmed", "Tuseef")
    second = ("Tufeeq", "Asif", "Afridi", "Khan", "Hasnat", "Zahoor", "Utba", "Rasheed", "Ashfaq", "Yaqoob", "Rehmat", "Inayat",
    "Sami", "Zeeshan", "Ajmal", "Javed", "Kamal", "Khalid", "Aziz")
    first = random.choice(first)
    return first

def generate_random_last_name():
    second = (
        "Tufeeq", "Asif", "Afridi", "Khan", "Hasnat", "Zahoor", "Utba", "Rasheed", "Ashfaq", "Yaqoob", "Rehmat",
        "Inayat",
        "Sami", "Zeeshan", "Ajmal", "Javed", "Kamal", "Khalid", "Aziz")
    second= random.choice(second)
    return second
    # seccond = random.choice(second)
    # name = (firrst + " " + seccond)
    # return name


def generate_random_adress():
    area= ("Korangi", "Liaqatabad", "Nagin chorancgi", "Bhens cololony", "college road", "stadium road", "school road", "madina market", "Housing colony", "Rehamandbad", "Mughal pura", "Baghban Pura",
    "Muradabad", "School Muhalla", "Safoora", "Atomic Colony", "PAF Colony", "Gulberg", "DHA")
    city= ("Islamabad", "Karachi", "Lahore", "Hydrabad", "Sheikhupura", "Multan", "Sargodha")
    house_number = "House Number" + " " + str(random.randint(1, 100))
    street_name="Street"+" "+str(random.randint(1,100))
    area = random.choice(area)
    city = random.choice(city)
    adress=house_number+" "+street_name+" "+area+" "+city
    return adress

def generate_random_card_number():
    random_wrong_number=str(generate_phone_number())
    card_numbers_collection=("4242424242424242","36227206271668","4000056655665556","5555555555554444","2223003122003222","5200828282828210",random_wrong_number,random_wrong_number,random_wrong_number,random_wrong_number)
    number=random.choice(card_numbers_collection)
    return str(number)

def generate_random_date():
    #05/27
    month="0"+str(random.randint(1,9))
    year=str(random.randint(20,30))
    date=str(month+"/"+year)
    return str(date)

def generate_random_quantity(upperlimit):
    number=random.randint(1,upperlimit)
    return str(number)




def generate_random_zipcodes():
    zipcode=random.randint(11111,99999)
    return str(zipcode)

def generate_random_email():
    name=generate_random_first_name()+generate_random_last_name()
    random_num=str(random.randint(1,99999))
    end_literal="@vizteck.com"
    email=name+random_num+end_literal
    email=email.strip()
    return email.lower()




def generate_random_city():
    city = ("Islamabad", "Karachi", "Lahore", "Hydrabad", "Sheikhupura", "Multan", "Sargodha")
    city = random.choice(city)
    return city




#false values
def generate_bad_phone_number():
    return str("bad"+generate_phone_number()+"bad")
# for i in range(1,450):
#     print("Sample****", i)
# adress1 = generate_random_adress()
# adress2 = generate_random_adress()
# name = generate_random_name()
# phone_number = phone = generate_phone_number()
    # print("Adress1", adress1)
    # print("Adress2", adress2)
    # print("Name", generate_random_name())
    # print("Carld Holder Name", name)
    # print("Phone Number", phone_number)

def generate_bad_date():
    return str(get_random_string(5))


def generate_bad_zip_code():
    return str(get_random_string(5))


def generate_bad_city():
    return str(random.randint(11111,99999))



def generate_bad_email():
    name = generate_random_first_name() + generate_random_last_name()
    random_num = str(random.randint(1, 99999))
    email = name + random_num
    return email.lower()








def companies_list():
    comapnies_list = [
        "Wal-Mart Stores",
        "Exxon Mobil",
        "Chevron",
        "Berkshire Hathaway",
        "Apple",
        "Phillips 66",
        "General Motors",
        "Ford Motor",
        "General Electric",
        "Valero Energy",
        "AT&T",
        "CVS Caremark",
        "Fannie Mae",
        "UnitedHealth Group",
        "McKesson",
        "Verizon Communications",
        "Hewlett-Packard",
        "J.P. Morgan Chase & Co.",
        "Costco Wholesale",
        "Express Scripts Holding",
        "Bank of America",
        "Cardinal Health",
        "International Business Machines",
        "Kroger",
        "Marathon Petroleum",
        "Citigroup",
        "Archer Daniels Midland",
        "AmerisourceBergen",
        "Wells Fargo",
        "Boeing",
        "Procter & Gamble",
        "Freddie Mac",
        "Home Depot",
        "Microsoft",
        "Amazon.com",
        "Target",
        "Walgreen Co.",
        "WellPoint",
        "Johnson & Johnson",
        "American International Group",
        "State Farm Insurance Cos.",
        "MetLife",
        "PepsiCo",
        "Comcast",
        "United Technologies",
        "Google",
        "ConocoPhillips",
        "Dow Chemical",
        "Caterpillar",
        "United Parcel Service",
        "Pfizer",
        "Lowe’s Companies",
        "Intel Corporation",
        "Energy Transfer Equity, L.P.",
        "Cisco Systems, Inc.",
        "Enterprise Products Partners L.P.",
        "Aetna Inc.",
        "The Coca-Cola Company",
        "Lockheed Martin Corporation",
        "Best Buy Co., Inc.",
        "The Walt Disney Company",
        "CHS Inc.",
        "Sysco Corporation",
        "FedEx Corporation",
        "Merck & Co., Inc.",
        "INTL FCStone Inc.",
        "Safeway Inc.",
        "Johnson Controls, Inc.",
        "Ingram Micro Inc.",
        "Plains GP Holdings, L.P.",
        "World Fuel Services Corporation",
        "Prudential Financial, Inc.",
        "Humana Inc.",
        "The Goldman Sachs Group, Inc.",
        "Tesoro Corporation",
        "Liberty Mutual Holding Company Inc.",
        "Honeywell International Inc.",
        "United Continental Holdings, Inc.",
        "HCA Holdings, Inc.",
        "Deere & Company",
        "Delta Air Lines, Inc.",
        "Oracle Corporation",
        "Morgan Stanley",
        "Hess Corporation",
        "Twenty-First Century Fox, Inc.",
        "E.I. du Pont de Nemours and Company",
        "Sears Holdings Corporation",
        "New York Life Insurance Company",
        "Mondelez International, Inc.",
        "American Express Company",
        "Nationwide Mutual Insurance Co.",
        "The Allstate Corporation",
        "Tyson Foods, Inc.",
        "Supervalu Inc.",
        "TIAA-CREF",
        "Massachusetts Mutual Life Insurance Company",
        "CIGNA Corporation",
        "DIRECTV",
        "General Dynamics Corporation",
        "Philip Morris International Inc.",
        "3M Company",
        "Time Warner Inc.",
        "Halliburton Company",
        "Publix Super Markets, Inc.",
        "International Paper Company",
        "McDonald’s Corporation",
        "Macy’s, Inc.",
        "The TJX Companies, Inc.",
        "Fluor Corporation",
        "Northwestern Mutual Life Insurance Company,Inc.",
        "Tech Data Corporation",
        "American Airlines Group Inc.",
        "The Hartford Financial Services Group, Inc.",
        "The Travelers Companies, Inc.",
        "Nike, Inc.",
        "Occidental Petroleum Corporation",
        "Avnet, Inc.",
        "Rite Aid Corporation",
        "Exelon Corporation",
        "Qualcomm Incorporated",
        "Emerson Electric Co.",
        "Northrop Grumman Corporation",
        "Duke Energy Corporation",
        "Capital One Financial Corporation",
        "Aflac Incorporated",
        "Raytheon Company",
        "Staples, Inc.",
        "EMC Corporation",
        "Eli Lilly and Company",
        "Alcoa Inc.",
        "National Oilwell Varco, Inc.",
        "Baker Hughes Incorporated",
        "US Foods, Inc.",
        "Time Warner Cable Inc.",
        "Union Pacific Corporation",
        "Abbott Laboratories",
        "Xerox Corporation",
        "Arrow Electronics, Inc",
        "Kimberly-Clark Corporation",
        "U.S. Bancorp",
        "United Services Automobile Association",
        "Freeport-McMoRan Copper & Gold Inc.",
        "Icahn Enterprises L.P.",
        "ManpowerGroup Inc.",
        "HollyFrontier Corporation",
        "Global Partners LP",
        "The Goodyear Tire & Rubber Company",
        "PBF Energy Inc.",
        "Danaher Corporation",
        "Nucor Corporation",
        "Kohl’s Corporation",
        "AbbVie Inc.",
        "Whirlpool Corporation",
        "Amgen Inc.",
        "Jabil Circuit, Inc.",
        "Kraft Foods Group, Inc.",
        "The Progressive Corporation",
        "CenturyLink, Inc.",
        "General Mills, Inc.",
        "Southwest Airlines Co.",
        "Altria Group, Inc.",
        "AutoNation, Inc.",
        "Chesapeake Energy Corporation",
        "Dollar General Corporation",
        "TRW Automotive Holdings Corp.",
        "United States Steel Corporation",
        "Colgate-Palmolive Company",
        "Cummins Inc.",
        "PACCAR Inc",
        "The Southern Company",
        "Illinois Tool Works Inc.",
        "The PNC Financial Services Group, Inc.",
        "Medtronic, Inc.",
        "The AES Corporation",
        "Murphy USA Inc.",
        "Bristol-Myers Squibb Company",
        "Lear Corporation",
        "The Gap, Inc.",
        "Apache Corporation",
        "eBay Inc.",
        "The Bank of New York Mellon Corporation",
        "CBS Corporation",
        "PG&E Corporation",
        "ConAgra Foods, Inc.",
        "Computer Sciences Corporation",
        "American Electric Power Company, Inc.",
        "Western Digital Corporation",
        "Marathon Oil Corporation",
        "Baxter International Inc.",
        "PPG Industries, Inc.",
        "NextEra Energy, Inc.",
        "Community Health Systems, Inc.",
        "Loews Corporation",
        "Penske Automotive Group, Inc.",
        "FirstEnergy Corp.",
        "Starbucks Corporation",
        "Monsanto Company",
        "Kellogg Company",
        "Land O’Lakes, Inc.",
        "ONEOK, Inc.",
        "Omnicom Group Inc.",
        "Anadarko Petroleum Corporation",
        "EOG Resources, Inc.",
        "DISH Network Corporation",
        "Genuine Parts Company",
        "Kinder Morgan, Inc.",
        "Waste Management, Inc.",
        "The Chubb Corporation",
        "Aramark Holdings Corporation",
        "Viacom Inc.",
        "Las Vegas Sands Corp.",
        "Dominion Resources, Inc.",
        "Ecolab Inc.",
        "Smithfield Foods, Inc.",
        "Thermo Fisher Scientific Inc.",
        "Yum! Brands, Inc.",
        "Parker-Hannifin Corporation",
        "Whole Foods Market, Inc.",
        "Marriott International, Inc.",
        "C. H. Robinson Worldwide, Inc.",
        "L-3 Communications Holdings, Inc.",
        "Edison International",
        "Toys “R” Us, Inc.",
        "Nordstrom, Inc.",
        "Consolidated Edison, Inc.",
        "Marsh & McLennan Companies, Inc.",
        "Texas Instruments Incorporated",
        "Textron Inc.",
        "Tenet Healthcare Corporation",
        "DaVita HealthCare Partners Inc.",
        "CSX Corporation",
        "Lincoln National Corporation",
        "Praxair, Inc.",
        "PPL Corporation",
        "J.C. Penney Company, Inc.",
        "Peter Kiewit Sons’, Inc.",
        "Jacobs Engineering Group Inc.",
        "Visa Inc.",
        "H.J. Heinz Company",
        "CarMax, Inc.",
        "V.F. Corporation",
        "Entergy Corporation",
        "Automatic Data Processing, Inc.",
        "NRG Energy, Inc.",
        "Guardian Life Ins. Co. of America",
        "Liberty Interactive Corporation",
        "Norfolk Southern Corporation",
        "Office Depot, Inc.",
        "Ameriprise Financial, Inc.",
        "Gilead Sciences, Inc.",
        "Centene Corporation",
        "Leucadia National Corporation",
        "Huntsman Corporation",
        "Health Net, Inc.",
        "Stanley Black & Decker, Inc.",
        "URS Corporation",
        "Xcel Energy Inc.",
        "Bed Bath & Beyond Inc.",
        "Navistar International Corporation",
        "Synnex Corporation",
        "First Data Corporation",
        "AGCO Corporation",
        "L Brands, Inc.",
        "Hertz Global Holdings, Inc.",
        "CDW Corporation",
        "CST Brands, Inc.",
        "Sempra Energy",
        "R.R. Donnelley & Sons Company",
        "BB&T Corporation",
        "Devon Energy Corporation",
        "Family Dollar Stores, Inc.",
        "Unum Group",
        "Ally Financial Inc.",
        "Reinsurance Group of America, Incorporated",
        "State Street Corporation",
        "Air Products & Chemicals, Inc.",
        "Ross Stores, Inc.",
        "The Sherwin-Williams Company",
        "The Estée Lauder Companies Inc.",
        "BlackRock, Inc.",
        "Western Refining, Inc.",
        "Avon Products, Inc.",
        "The Mosaic Company",
        "Public Service Enterprise Group Incorporated",
        "Dean Foods Company",
        "Cameron International Corporation",
        "MGM Resorts International",
        "KKR & Co. L.P.",
        "Hilton Worldwide Holdings Inc.",
        "DTE Energy Company",
        "Genworth Financial, Inc.",
        "Henry Schein, Inc.",
        "Rock-Tenn Company",
        "WellCare Health Plans, Inc.",
        "W.W. Grainger, Inc.",
        "Discover Financial Services",
        "Eastman Chemical Company",
        "Principal Financial Group, Inc.",
        "Reliance Steel & Aluminum Co.",
        "AutoZone, Inc.",
        "Dover Corporation",
        "Micron Technology, Inc.",
        "Owens & Minor, Inc.",
        "Assurant, Inc.",
        "GameStop Corp.",
        "Stryker Corporation",
        "Group 1 Automotive, Inc.",
        "Cognizant Technology Solutions Corporation",
        "Sonic Automotive, Inc.",
        "Autoliv, Inc.",
        "Hormel Foods Corporation",
        "Motorola Solutions, Inc.",
        "Crown Holdings, Inc.",
        "SunTrust Banks, Inc.",
        "Campbell Soup Company",
        "Fidelity National Financial, Inc.",
        "HD Supply Holdings, Inc.",
        "Caesars Entertainment Corporation",
        "Darden Restaurants, Inc.",
        "Weyerhaeuser Company",
        "Ball Corporation",
        "Precision Castparts Corp.",
        "Masco Corporation",
        "Universal Health Services, Inc.",
        "Republic Services, Inc.",
        "MasterCard Incorporated",
        "Newmont Mining Corporation",
        "Broadcom Corporation",
        "Reynolds American Inc.",
        "PVH Corp.",
        "Charter Communications, Inc.",
        "AECOM Technology Corporation",
        "CenterPoint Energy, Inc.",
        "Pacific Life",
        "Thrivent Financial for Lutherans",
        "Becton, Dickinson and Company",
        "Franklin Resources, Inc.",
        "Tenneco Inc.",
        "TravelCenters of America LLC",
        "Avis Budget Group, Inc.",
        "Facebook, Inc.",
        "Dollar Tree, Inc.",
        "Corning Incorporated",
        "Ashland Inc.",
        "Sealed Air Corporation",
        "Core-Mark Holding Company, Inc.",
        "Oshkosh Corporation",
        "Coca-Cola Enterprises, Inc.",
        "WESCO International, Inc.",
        "Applied Materials, Inc.",
        "Visteon Corporation",
        "BorgWarner Inc.",
        "Spectrum Group International, Inc.",
        "Oaktree Capital Group, LLC",
        "Steel Dynamics, Inc.",
        "Jarden Corporation",
        "Mohawk Industries, Inc.",
        "Terex Corporation",
        "Northeast Utilities",
        "KBR, Inc.",
        "Fifth Third Bancorp",
        "UGI Corporation",
        "CBRE Group, Inc.",
        "Quest Diagnostics Incorporated",
        "Peabody Energy Corporation",
        "The Hershey Company",
        "Boston Scientific Corporation",
        "FMC Technologies, Inc.",
        "The Interpublic Group of Companies, Inc.",
        "Commercial Metals Company",
        "The Pantry, Inc.",
        "Owens-Illinois, Inc.",
        "American Family Ins. Group",
        "Ralph Lauren Corporation",
        "Biogen Idec Inc.",
        "PetSmart, Inc.",
        "Mylan Inc.",
        "Symantec Corporation",
        "Ameren Corporation",
        "The Williams Companies, Inc.",
        "Barnes & Noble, Inc.",
        "Huntington Ingalls Industries, Inc.",
        "The Priceline Group Inc.",
        "Agilent Technologies, Inc.",
        "Dana Holding Corporation",
        "Dillard’s, Inc.",
        "Seaboard Corporation",
        "Vanguard Health Systems, Inc.",
        "Casey’s General Stores, Inc.",
        "O’Reilly Automotive, Inc.",
        "The Blackstone Group L.P.",
        "Mutual of Omaha Insurance Company",
        "Molina Healthcare, Inc.",
        "CMS Energy Corporation",
        "Targa Resources Corp.",
        "Quanta Services, Inc.",
        "Cablevision Systems Corporation",
        "Avery Dennison Corporation",
        "Celanese Corporation",
        "Foot Locker, Inc.",
        "Celgene Corporation",
        "Advance Auto Parts, Inc.",
        "Mattel, Inc.",
        "Live Nation Entertainment, Inc.",
        "General Cable Corporation",
        "Ryder System, Inc.",
        "EMCOR Group, Inc.",
        "Allergan, Inc.",
        "W.R. Berkley Corporation",
        "Rockwell Automation, Inc.",
        "NetApp, Inc.",
        "Ingredion Incorporated",
        "Level 3 Communications, Inc.",
        "Calpine Corporation",
        "Omnicare, Inc.",
        "Erie Insurance Group",
        "SLM Corporation",
        "D.R. Horton, Inc.",
        "CC Media Holdings, Inc.",
        "Anixter International Inc.",
        "Dick’s Sporting Goods, Inc.",
        "SanDisk Corporation",
        "NCR Corporation",
        "Starwood Hotels & Resorts Worldwide, Inc.",
        "Expeditors International of Washington, Inc.",
        "Fidelity National Information Services, Inc.",
        "United Natural Foods, Inc.",
        "Auto-Owners Insurance Group",
        "Windstream Holdings, Inc.",
        "Dr Pepper Snapple Group, Inc.",
        "Lennar Corporation",
        "Sanmina",
        "Harley-Davidson, Inc.",
        "CONSOL Energy Inc.",
        "The J.M. Smucker Company",
        "Newell Rubbermaid Inc.",
        "CH2M HILL Companies, Ltd.",
        "Energy Future Holdings Corp.",
        "Susser Holdings Corporation",
        "Laboratory Corporation of America Holdings",
        "Kindred Healthcare, Inc.",
        "Leidos Holdings Inc.",
        "Booz Allen Hamilton Holding Corp.",
        "The Jones Financial Companies,L.L.L.P.",
        "Cliffs Natural Resources Inc.",
        "PulteGroup, Inc.",
        "Regions Financial Corporation",
        "NiSource Inc.",
        "Graybar Electric Company, Inc.",
        "Integrys Energy Group, Inc.",
        "The Clorox Company",
        "Wynn Resorts, Limited",
        "The Andersons, Inc.",
        "J.B. Hunt Transport Services, Inc.",
        "AK Steel Holding Corporation",
        "Harbinger Group Inc.",
        "MeadWestvaco Corporation",
        "The Western Union Company",
        "The Charles Schwab Corporation",
        "Discovery Communications, Inc.",
        "Spectra Energy Corp",
        "St. Jude Medical, Inc.",
        "CF Industries Holdings, Inc.",
        "Con-way Inc.",
        "Old Republic International Corporation",
        "JetBlue Airways Corporation",
        "Calumet Specialty Products Partners, L.P.",
        "Kelly Services, Inc.",
        "Domtar Corporation",
        "Murphy Oil Corporation",
        "Harris Corporation",
        "Asbury Automotive Group, Inc.",
        "Big Lots, Inc.",
        "Advanced Micro Devices, Inc.",
        "Owens Corning",
        "Realogy Holdings Corp.",
        "Host Hotels & Resorts, Inc.",
        "MRC Global Inc.",
        "Simon Property Group, Inc.",
        "Tractor Supply Company",
        "Gannett Co., Inc.",
        "Alaska Air Group, Inc.",
        "Insight Enterprises, Inc.",
        "McGraw Hill Financial, Inc.",
        "Buckeye Partners, L.P.",
        "Quintiles Transnational Holdings Inc.",
        "American Financial Group, Inc.",
        "United Stationers Inc.",
        "Coach, Inc.",
        "LKQ Corporation",
        "Noble Energy, Inc.",
        "Bemis Company, Inc.",
        "Joy Global Inc.",
        "Wyndham Worldwide Corporation",
        "NII Holdings, Inc.",
        "Lorillard, Inc.",
        "Alleghany Corporation",
        "Airgas, Inc.",
        "First American Financial Corporation",
        "United Rentals, Inc."
    ]
    company = random.choice(comapnies_list)
    return company



def getimagelist():
    piclist = [{
        'id': 'AQ7JEEEMum8',
        'created_at': '2020-10-12T13:46:27-04:00',
        'updated_at': '2020-11-10T05:17:35-05:00',
        'promoted_at': None,
        'width': 5792,
        'height': 8688,
        'color': '#F1F3F5',
        'blur_hash': 'LJAdTbQ+RjR,?cVY%1NH#3M}t7Ne',
        'description': None,
        'alt_description': 'blue and white box on black textile',
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1602524209335-0224ee211de5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1602524209335-0224ee211de5?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1602524209335-0224ee211de5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1602524209335-0224ee211de5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1602524209335-0224ee211de5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/AQ7JEEEMum8',
            'html': 'https://unsplash.com/photos/AQ7JEEEMum8',
            'download': 'https://unsplash.com/photos/AQ7JEEEMum8/download',
            'download_location': 'https://api.unsplash.com/photos/AQ7JEEEMum8/download'
        },
        'categories': [],
        'likes': 22,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': {
            'impression_urls': [],
            'tagline': 'Memory for life',
            'tagline_url': 'https://www.samsung.com/us/memory-storage/',
            'sponsor': {
                'id': 'eySMK9KwmJU',
                'updated_at': '2020-11-11T04:35:20-05:00',
                'username': 'samsungmemory',
                'name': 'Samsung Memory',
                'first_name': 'Samsung',
                'last_name': 'Memory',
                'twitter_username': '',
                'portfolio_url': 'http://www.samsung.com/us/computing/memory-storage/',
                'bio': 'Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.',
                'location': None,
                'links': {
                    'self': 'https://api.unsplash.com/users/samsungmemory',
                    'html': 'https://unsplash.com/@samsungmemory',
                    'photos': 'https://api.unsplash.com/users/samsungmemory/photos',
                    'likes': 'https://api.unsplash.com/users/samsungmemory/likes',
                    'portfolio': 'https://api.unsplash.com/users/samsungmemory/portfolio',
                    'following': 'https://api.unsplash.com/users/samsungmemory/following',
                    'followers': 'https://api.unsplash.com/users/samsungmemory/followers'
                },
                'profile_image': {
                    'small': 'https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                    'medium': 'https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                    'large': 'https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
                },
                'instagram_username': 'samsungmemory',
                'total_collections': 0,
                'total_likes': 0,
                'total_photos': 60,
                'accepted_tos': True
            }
        },
        'user': {
            'id': 'eySMK9KwmJU',
            'updated_at': '2020-11-11T04:35:20-05:00',
            'username': 'samsungmemory',
            'name': 'Samsung Memory',
            'first_name': 'Samsung',
            'last_name': 'Memory',
            'twitter_username': '',
            'portfolio_url': 'http://www.samsung.com/us/computing/memory-storage/',
            'bio': 'Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.',
            'location': None,
            'links': {
                'self': 'https://api.unsplash.com/users/samsungmemory',
                'html': 'https://unsplash.com/@samsungmemory',
                'photos': 'https://api.unsplash.com/users/samsungmemory/photos',
                'likes': 'https://api.unsplash.com/users/samsungmemory/likes',
                'portfolio': 'https://api.unsplash.com/users/samsungmemory/portfolio',
                'following': 'https://api.unsplash.com/users/samsungmemory/following',
                'followers': 'https://api.unsplash.com/users/samsungmemory/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'samsungmemory',
            'total_collections': 0,
            'total_likes': 0,
            'total_photos': 60,
            'accepted_tos': True
        }
    }, {
        'id': 'mp0T78lo0hg',
        'created_at': '2020-11-10T11:51:41-05:00',
        'updated_at': '2020-11-11T04:36:58-05:00',
        'promoted_at': '2020-11-11T04:36:01-05:00',
        'width': 2519,
        'height': 3778,
        'color': '#FEF2DD',
        'blur_hash': 'LYDR{8oL9bWV-ojtRkay0#WV-nj[',
        'description': 'End of day',
        'alt_description': None,
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605026187659-a83756e22e43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605026187659-a83756e22e43?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605026187659-a83756e22e43?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605026187659-a83756e22e43?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605026187659-a83756e22e43?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/mp0T78lo0hg',
            'html': 'https://unsplash.com/photos/mp0T78lo0hg',
            'download': 'https://unsplash.com/photos/mp0T78lo0hg/download',
            'download_location': 'https://api.unsplash.com/photos/mp0T78lo0hg/download'
        },
        'categories': [],
        'likes': 1,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'AHC-U6I0Kdg',
            'updated_at': '2020-11-11T04:36:01-05:00',
            'username': 'huefnerdesign',
            'name': 'Tim Hüfner',
            'first_name': 'Tim',
            'last_name': 'Hüfner',
            'twitter_username': None,
            'portfolio_url': 'http://huefner-design.de/',
            'bio': 'Freelance graphic designer and creative director. I love to design: simple, elegant and timeless brand identities, mobile applications and websites - with focus on core content and product. And recently I have also discovered photography for myself.',
            'location': 'Munich',
            'links': {
                'self': 'https://api.unsplash.com/users/huefnerdesign',
                'html': 'https://unsplash.com/@huefnerdesign',
                'photos': 'https://api.unsplash.com/users/huefnerdesign/photos',
                'likes': 'https://api.unsplash.com/users/huefnerdesign/likes',
                'portfolio': 'https://api.unsplash.com/users/huefnerdesign/portfolio',
                'following': 'https://api.unsplash.com/users/huefnerdesign/following',
                'followers': 'https://api.unsplash.com/users/huefnerdesign/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1597825399968-a82d500a793fimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1597825399968-a82d500a793fimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1597825399968-a82d500a793fimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'timhuefner',
            'total_collections': 0,
            'total_likes': 0,
            'total_photos': 172,
            'accepted_tos': True
        }
    }, {
        'id': 'I7BFheLFsjU',
        'created_at': '2020-11-10T16:39:06-05:00',
        'updated_at': '2020-11-11T04:36:58-05:00',
        'promoted_at': '2020-11-11T04:33:01-05:00',
        'width': 7492,
        'height': 4997,
        'color': '#0A2C57',
        'blur_hash': 'LLD0{XNGNzs:8^t9kDWBPE%3nhS2',
        'description': 'A cold morning in the Carpathian Mountains.',
        'alt_description': 'snow covered field under cloudy sky during daytime',
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605044308293-9f79856e6568?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605044308293-9f79856e6568?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605044308293-9f79856e6568?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605044308293-9f79856e6568?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605044308293-9f79856e6568?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/I7BFheLFsjU',
            'html': 'https://unsplash.com/photos/I7BFheLFsjU',
            'download': 'https://unsplash.com/photos/I7BFheLFsjU/download',
            'download_location': 'https://api.unsplash.com/photos/I7BFheLFsjU/download'
        },
        'categories': [],
        'likes': 0,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': '3XpdGI2fP_o',
            'updated_at': '2020-11-11T04:33:01-05:00',
            'username': 'danielmirlea',
            'name': 'Daniel Mirlea',
            'first_name': 'Daniel',
            'last_name': 'Mirlea',
            'twitter_username': None,
            'portfolio_url': 'http://www.danielmirlea.com',
            'bio': 'I believe that through photography every human can become more aware of the environmental issues, can be more interested and learn about the residents from the heart of the forest, and can discover something in himself/herself: the return to nature.',
            'location': 'Romania',
            'links': {
                'self': 'https://api.unsplash.com/users/danielmirlea',
                'html': 'https://unsplash.com/@danielmirlea',
                'photos': 'https://api.unsplash.com/users/danielmirlea/photos',
                'likes': 'https://api.unsplash.com/users/danielmirlea/likes',
                'portfolio': 'https://api.unsplash.com/users/danielmirlea/portfolio',
                'following': 'https://api.unsplash.com/users/danielmirlea/following',
                'followers': 'https://api.unsplash.com/users/danielmirlea/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-fb-1553694465-0a406797a61c.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-fb-1553694465-0a406797a61c.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-fb-1553694465-0a406797a61c.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'daniel_mirlea',
            'total_collections': 0,
            'total_likes': 1,
            'total_photos': 43,
            'accepted_tos': True
        }
    }, {
        'id': 'LXyEl3x_MQA',
        'created_at': '2020-11-10T12:10:54-05:00',
        'updated_at': '2020-11-11T04:30:01-05:00',
        'promoted_at': '2020-11-11T04:30:01-05:00',
        'width': 4093,
        'height': 5114,
        'color': '#CADAE5',
        'blur_hash': 'LTD+}FoL4mRj_3jYIAjZozWBs:t7',
        'description': None,
        'alt_description': None,
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605028241606-ca01277aa15c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605028241606-ca01277aa15c?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605028241606-ca01277aa15c?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605028241606-ca01277aa15c?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605028241606-ca01277aa15c?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/LXyEl3x_MQA',
            'html': 'https://unsplash.com/photos/LXyEl3x_MQA',
            'download': 'https://unsplash.com/photos/LXyEl3x_MQA/download',
            'download_location': 'https://api.unsplash.com/photos/LXyEl3x_MQA/download'
        },
        'categories': [],
        'likes': 3,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'TbgAvwSJqpU',
            'updated_at': '2020-11-11T04:35:28-05:00',
            'username': 'ianjbattaglia',
            'name': 'Ian Battaglia',
            'first_name': 'Ian',
            'last_name': 'Battaglia',
            'twitter_username': 'IanJBattaglia',
            'portfolio_url': 'http://monochromatic.co',
            'bio': "I'm a freelance photographer and writer in Chicago. Available for work. Email: ian@monochromatic.co\r\nI shoot Fujifilm cameras proudly. ",
            'location': 'Chicago',
            'links': {
                'self': 'https://api.unsplash.com/users/ianjbattaglia',
                'html': 'https://unsplash.com/@ianjbattaglia',
                'photos': 'https://api.unsplash.com/users/ianjbattaglia/photos',
                'likes': 'https://api.unsplash.com/users/ianjbattaglia/likes',
                'portfolio': 'https://api.unsplash.com/users/ianjbattaglia/portfolio',
                'following': 'https://api.unsplash.com/users/ianjbattaglia/following',
                'followers': 'https://api.unsplash.com/users/ianjbattaglia/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1552930708671-2a8ebeec9833?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1552930708671-2a8ebeec9833?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1552930708671-2a8ebeec9833?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'IanJBattaglia',
            'total_collections': 0,
            'total_likes': 10,
            'total_photos': 176,
            'accepted_tos': True
        }
    }, {
        'id': '4mHsCBUwPQ4',
        'created_at': '2020-11-10T12:06:14-05:00',
        'updated_at': '2020-11-11T04:27:03-05:00',
        'promoted_at': '2020-11-11T04:27:03-05:00',
        'width': 3648,
        'height': 5472,
        'color': '#0F120E',
        'blur_hash': 'LqJ*t}IUIU%M~qkCWVkC^,t6t6Rk',
        'description': 'Rural waterfall - Thailand',
        'alt_description': None,
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605025473042-862c89f018ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605025473042-862c89f018ff?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605025473042-862c89f018ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605025473042-862c89f018ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605025473042-862c89f018ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/4mHsCBUwPQ4',
            'html': 'https://unsplash.com/photos/4mHsCBUwPQ4',
            'download': 'https://unsplash.com/photos/4mHsCBUwPQ4/download',
            'download_location': 'https://api.unsplash.com/photos/4mHsCBUwPQ4/download'
        },
        'categories': [],
        'likes': 1,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'e9k-5qxCYDw',
            'updated_at': '2020-11-11T04:30:29-05:00',
            'username': 'robincanfield',
            'name': 'Robin Canfield',
            'first_name': 'Robin',
            'last_name': 'Canfield',
            'twitter_username': 'robincanfield',
            'portfolio_url': 'http://www.robincanfield.com',
            'bio': 'World traveling educator, explorer, journalist, writer; a catalyst for both documentaries and study abroad. I travel the globe to bring storytellers to changemakers to help bring their stories to the world.\r\n reach out anytime',
            'location': 'Florida, USA',
            'links': {
                'self': 'https://api.unsplash.com/users/robincanfield',
                'html': 'https://unsplash.com/@robincanfield',
                'photos': 'https://api.unsplash.com/users/robincanfield/photos',
                'likes': 'https://api.unsplash.com/users/robincanfield/likes',
                'portfolio': 'https://api.unsplash.com/users/robincanfield/portfolio',
                'following': 'https://api.unsplash.com/users/robincanfield/following',
                'followers': 'https://api.unsplash.com/users/robincanfield/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1588268188413-af25bdc9b01eimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1588268188413-af25bdc9b01eimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1588268188413-af25bdc9b01eimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'robin_shoots',
            'total_collections': 0,
            'total_likes': 90,
            'total_photos': 230,
            'accepted_tos': True
        }
    }, {
        'id': 'Aa6EQXqXWns',
        'created_at': '2020-11-10T23:03:08-05:00',
        'updated_at': '2020-11-11T04:24:03-05:00',
        'promoted_at': '2020-11-11T04:24:02-05:00',
        'width': 2838,
        'height': 3784,
        'color': '#DBE2F2',
        'blur_hash': 'LJJ7XhE0Os.8^k-V%NWE4TjE%29Z',
        'description': 'Asian Malaysian Chinese Cuisine Dark Soy Sauce Wonton Noodles with Barbequed Pork and Roasted Pork with Rice',
        'alt_description': 'white rice on white ceramic bowl',
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605067148806-cef90c6980fb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605067148806-cef90c6980fb?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605067148806-cef90c6980fb?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605067148806-cef90c6980fb?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605067148806-cef90c6980fb?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/Aa6EQXqXWns',
            'html': 'https://unsplash.com/photos/Aa6EQXqXWns',
            'download': 'https://unsplash.com/photos/Aa6EQXqXWns/download',
            'download_location': 'https://api.unsplash.com/photos/Aa6EQXqXWns/download'
        },
        'categories': [],
        'likes': 1,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'd87SdM9OSr8',
            'updated_at': '2020-11-11T04:30:27-05:00',
            'username': 'lukelung1991',
            'name': 'Luke Lung',
            'first_name': 'Luke',
            'last_name': 'Lung',
            'twitter_username': None,
            'portfolio_url': None,
            'bio': 'I am a graphic designer and a photography enthusiast. I enjoy taking photos of people and their moments; as well as styling props with other things I like. Most of the photos taken are with my iPhone but sometimes with my camera. ',
            'location': 'Kuala Lumpur, Malaysia',
            'links': {
                'self': 'https://api.unsplash.com/users/lukelung1991',
                'html': 'https://unsplash.com/@lukelung1991',
                'photos': 'https://api.unsplash.com/users/lukelung1991/photos',
                'likes': 'https://api.unsplash.com/users/lukelung1991/likes',
                'portfolio': 'https://api.unsplash.com/users/lukelung1991/portfolio',
                'following': 'https://api.unsplash.com/users/lukelung1991/following',
                'followers': 'https://api.unsplash.com/users/lukelung1991/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1570459350594-2544a8d74fc5image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1570459350594-2544a8d74fc5image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1570459350594-2544a8d74fc5image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'lukelung1991',
            'total_collections': 1,
            'total_likes': 48,
            'total_photos': 16,
            'accepted_tos': True
        }
    }, {
        'id': '01g_ODEi4vI',
        'created_at': '2020-11-10T19:58:07-05:00',
        'updated_at': '2020-11-11T04:21:03-05:00',
        'promoted_at': '2020-11-11T04:21:03-05:00',
        'width': 4000,
        'height': 6000,
        'color': '#EFEFEF',
        'blur_hash': None,
        'description': 'growing frond of this neighborhood \n\ninsta @carterr_',
        'alt_description': 'green banana tree beside white wooden house',
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605056255208-3c2db968f992?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605056255208-3c2db968f992?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605056255208-3c2db968f992?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605056255208-3c2db968f992?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605056255208-3c2db968f992?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/01g_ODEi4vI',
            'html': 'https://unsplash.com/photos/01g_ODEi4vI',
            'download': 'https://unsplash.com/photos/01g_ODEi4vI/download',
            'download_location': 'https://api.unsplash.com/photos/01g_ODEi4vI/download'
        },
        'categories': [],
        'likes': 2,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': '33DXoEvkalc',
            'updated_at': '2020-11-11T04:30:25-05:00',
            'username': 'carterbaran',
            'name': 'Carter Baran',
            'first_name': 'Carter',
            'last_name': 'Baran',
            'twitter_username': None,
            'portfolio_url': None,
            'bio': 'IG: Carterr_',
            'location': None,
            'links': {
                'self': 'https://api.unsplash.com/users/carterbaran',
                'html': 'https://unsplash.com/@carterbaran',
                'photos': 'https://api.unsplash.com/users/carterbaran/photos',
                'likes': 'https://api.unsplash.com/users/carterbaran/likes',
                'portfolio': 'https://api.unsplash.com/users/carterbaran/portfolio',
                'following': 'https://api.unsplash.com/users/carterbaran/following',
                'followers': 'https://api.unsplash.com/users/carterbaran/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1604790892850-751dae81d3dbimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1604790892850-751dae81d3dbimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1604790892850-751dae81d3dbimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'carterr_',
            'total_collections': 0,
            'total_likes': 19,
            'total_photos': 27,
            'accepted_tos': True
        }
    }, {
        'id': 'iEKm1ULALZU',
        'created_at': '2020-11-10T13:34:44-05:00',
        'updated_at': '2020-11-11T04:19:11-05:00',
        'promoted_at': '2020-11-11T04:19:11-05:00',
        'width': 3456,
        'height': 5184,
        'color': '#EFD1C5',
        'blur_hash': 'LLBDWlHr?bs.~pVX%M%L?bMxs:xu',
        'description': None,
        'alt_description': None,
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605032992136-f3272ae1d707?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605032992136-f3272ae1d707?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605032992136-f3272ae1d707?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605032992136-f3272ae1d707?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605032992136-f3272ae1d707?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/iEKm1ULALZU',
            'html': 'https://unsplash.com/photos/iEKm1ULALZU',
            'download': 'https://unsplash.com/photos/iEKm1ULALZU/download',
            'download_location': 'https://api.unsplash.com/photos/iEKm1ULALZU/download'
        },
        'categories': [],
        'likes': 0,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'GQM9XmcHUog',
            'updated_at': '2020-11-11T04:19:11-05:00',
            'username': 'iamgessyy',
            'name': 'Robin Gislain Shumbusho',
            'first_name': 'Robin Gislain',
            'last_name': 'Shumbusho',
            'twitter_username': None,
            'portfolio_url': 'https://iamgessyy.wixsite.com/portfolio/online-store',
            'bio': 'Rwandan Fashion and Editorial photographer - currently in canada booking Montreal and PEI. Tag me on instagram (@iamgessyy) would love to see your work and connect.',
            'location': 'Canada',
            'links': {
                'self': 'https://api.unsplash.com/users/iamgessyy',
                'html': 'https://unsplash.com/@iamgessyy',
                'photos': 'https://api.unsplash.com/users/iamgessyy/photos',
                'likes': 'https://api.unsplash.com/users/iamgessyy/likes',
                'portfolio': 'https://api.unsplash.com/users/iamgessyy/portfolio',
                'following': 'https://api.unsplash.com/users/iamgessyy/following',
                'followers': 'https://api.unsplash.com/users/iamgessyy/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-1601510661969-62193d69bcf4image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-1601510661969-62193d69bcf4image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-1601510661969-62193d69bcf4image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'iamgessyy',
            'total_collections': 0,
            'total_likes': 20,
            'total_photos': 39,
            'accepted_tos': True
        }
    }, {
        'id': '-pnawSG96Ls',
        'created_at': '2020-11-10T11:44:16-05:00',
        'updated_at': '2020-11-11T04:18:03-05:00',
        'promoted_at': '2020-11-11T04:18:03-05:00',
        'width': 6000,
        'height': 4000,
        'color': '#0E0E0E',
        'blur_hash': 'L,Hf0WRjkCn$?wR*j]ofNefljYog',
        'description': 'my instagram: @didiofederico\nif you want, credit me by linking back on my website www.fdsmilano.it and tag me on instagram :)',
        'alt_description': 'waterfalls near brown mountain under blue sky during daytime',
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605025169915-987049301f31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605025169915-987049301f31?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605025169915-987049301f31?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605025169915-987049301f31?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605025169915-987049301f31?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/-pnawSG96Ls',
            'html': 'https://unsplash.com/photos/-pnawSG96Ls',
            'download': 'https://unsplash.com/photos/-pnawSG96Ls/download',
            'download_location': 'https://api.unsplash.com/photos/-pnawSG96Ls/download'
        },
        'categories': [],
        'likes': 3,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'dVFMTiYtyUY',
            'updated_at': '2020-11-11T04:30:35-05:00',
            'username': 'didiofederico',
            'name': 'Federico Di Dio',
            'first_name': 'Federico',
            'last_name': 'Di Dio',
            'twitter_username': None,
            'portfolio_url': 'http://www.fdsmilano.it',
            'bio': 'photographer |traveler | adventure and nature lover\r\nmy instagram: @didiofederico.    Thanks for using my photos! if you want, credit me by linking back to my website www.fdsmilano.it and by using the tag @didiofederico on instagram!',
            'location': 'Milano',
            'links': {
                'self': 'https://api.unsplash.com/users/didiofederico',
                'html': 'https://unsplash.com/@didiofederico',
                'photos': 'https://api.unsplash.com/users/didiofederico/photos',
                'likes': 'https://api.unsplash.com/users/didiofederico/likes',
                'portfolio': 'https://api.unsplash.com/users/didiofederico/portfolio',
                'following': 'https://api.unsplash.com/users/didiofederico/following',
                'followers': 'https://api.unsplash.com/users/didiofederico/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-fb-1604429667-1700af613d59.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-fb-1604429667-1700af613d59.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-fb-1604429667-1700af613d59.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'didiofederico',
            'total_collections': 1,
            'total_likes': 0,
            'total_photos': 61,
            'accepted_tos': True
        }
    }, {
        'id': 'giDVF1QyKcs',
        'created_at': '2020-11-10T13:59:33-05:00',
        'updated_at': '2020-11-11T04:16:31-05:00',
        'promoted_at': '2020-11-11T04:16:31-05:00',
        'width': 2844,
        'height': 4266,
        'color': '#150E0F',
        'blur_hash': 'LPMa9ORP.S9FS|afSgM{EgMy4Tt7',
        'description': 'Chocolate pie @martindearriba',
        'alt_description': None,
        'urls': {
            'raw': 'https://images.unsplash.com/photo-1605034733358-264cf9d966d1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'full': 'https://images.unsplash.com/photo-1605034733358-264cf9d966d1?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'regular': 'https://images.unsplash.com/photo-1605034733358-264cf9d966d1?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'small': 'https://images.unsplash.com/photo-1605034733358-264cf9d966d1?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0',
            'thumb': 'https://images.unsplash.com/photo-1605034733358-264cf9d966d1?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3OTM0Nn0'
        },
        'links': {
            'self': 'https://api.unsplash.com/photos/giDVF1QyKcs',
            'html': 'https://unsplash.com/photos/giDVF1QyKcs',
            'download': 'https://unsplash.com/photos/giDVF1QyKcs/download',
            'download_location': 'https://api.unsplash.com/photos/giDVF1QyKcs/download'
        },
        'categories': [],
        'likes': 2,
        'liked_by_user': False,
        'current_user_collections': [],
        'sponsorship': None,
        'user': {
            'id': 'i_oQWlXs-J4',
            'updated_at': '2020-11-11T04:16:48-05:00',
            'username': 'martindearriba',
            'name': 'Martin de Arriba',
            'first_name': 'Martin',
            'last_name': 'de Arriba',
            'twitter_username': 'martinderriba',
            'portfolio_url': 'http://www.martindearriba.com/',
            'bio': 'Martin de Arriba\r\nLOVE, #ART, #DESIGN & #DREAMS www.martindearriba.com',
            'location': None,
            'links': {
                'self': 'https://api.unsplash.com/users/martindearriba',
                'html': 'https://unsplash.com/@martindearriba',
                'photos': 'https://api.unsplash.com/users/martindearriba/photos',
                'likes': 'https://api.unsplash.com/users/martindearriba/likes',
                'portfolio': 'https://api.unsplash.com/users/martindearriba/portfolio',
                'following': 'https://api.unsplash.com/users/martindearriba/following',
                'followers': 'https://api.unsplash.com/users/martindearriba/followers'
            },
            'profile_image': {
                'small': 'https://images.unsplash.com/profile-fb-1523739765-f359f3629167.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32',
                'medium': 'https://images.unsplash.com/profile-fb-1523739765-f359f3629167.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64',
                'large': 'https://images.unsplash.com/profile-fb-1523739765-f359f3629167.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128'
            },
            'instagram_username': 'martindearriba',
            'total_collections': 4,
            'total_likes': 12,
            'total_photos': 35,
            'accepted_tos': True
        }
    }]

    customlist = []
    for i in range(1, len(piclist)):
        pic = piclist[i]['urls']['small']
        customlist.append(pic)


    # print(customlist)
    return customlist



def return_brand():
    brands_list = [
        "1&1",
        "10.or",
        "3222222 Satelital",
        "3Go",
        "3Q",
        "4good",
        "7Eleven",
        "7mobile",
        "9mobile",
        "A.O.I. ELECTRONICS FACTORY",
        "A1",
        "ACE France",
        "ACKEES",
        "ACT",
        "AG Mobile",
        "AKOR",
        "AMTC",
        "AMobile",
        "ANDRINO",
        "ANEE",
        "ANS",
        "AOC",
        "AOpen",
        "ASTCA",
        "ASTON",
        "AT&T",
        "ATM (Brazil)",
        "AURII",
        "AV",
        "AVH San Luis S.A.",
        "AXXA",
        "AZBox",
        "AZPEN",
        "Aamra WE",
        "Abocom",
        "Accent",
        "Access",
        "Acegame S.A.",
        "Acepad",
        "Acer",
        "Aceson",
        "Aconatic",
        "Adart",
        "Admiral Overseas Corporation",
        "Adreamer (Shenzhen)",
        "Advan digital",
        "Advance",
        "Advantage",
        "Advantage Air",
        "Aelion",
        "Aeon Communication (IN)",
        "Affix",
        "AfriOne",
        "Aikun",
        "Aimson",
        "Ainol",
        "AirTV",
        "Airpha",
        "Airtab",
        "Airtel",
        "Aiuto",
        "Aiwa",
        "Akai",
        "Akari",
        "Akino",
        "Alba",
        "Alco",
        "Alcor",
        "Aldo Mobile",
        "Algar",
        "Alhafidh",
        "Aligator",
        "AllCall",
        "AllView",
        "Alldocube",
        "Allducube",
        "Allfine",
        "Allouette",
        "Alpha",
        "Alphascan",
        "Altice",
        "Altron",
        "Americamovil",
        "Amgoo",
        "Aminocom",
        "Ampila",
        "Amplify",
        "Amstrad",
        "Andersson",
        "Antel",
        "Anydata",
        "Apex",
        "Aprix",
        "Aqua",
        "Arcelik",
        "Archos",
        "Ark",
        "Arris",
        "Arrow",
        "Artek",
        "Artel",
        "Artizlee",
        "Asanzo",
        "Ascom",
        "Ascom Wireless Solutions",
        "Ashna",
        "Ashtel",
        "Asianet",
        "Aspera",
        "Astak",
        "Astro",
        "Astro Queo",
        "AstroQueo",
        "Astro_Tab",
        "Astrom",
        "Asus",
        "AtGames-zooti",
        "Athesi",
        "Atria Convergence Technologies",
        "Attila",
        "Auchan",
        "Audi AG",
        "Audiovox",
        "Aura",
        "Auris",
        "Avaya",
        "Avion",
        "Avoca",
        "Avvio",
        "Axioo",
        "Axxa Mobile",
        "Azumi",
        "BARTEC",
        "BDQ",
        "BEISTA",
        "BGH S.A.",
        "BKAV",
        "BLECK",
        "BLOVEDREAM",
        "BLOW",
        "BLUEING",
        "BMPRO",
        "BMXC",
        "BMobile",
        "BQru",
        "BRAVA",
        "BRAVE",
        "BRIGMTON",
        "BTC Mobile",
        "BYD",
        "BYJUS",
        "Bang & Olufsen",
        "Bangho",
        "Barel",
        "Barnes and Noble",
        "Battcell",
        "Bauhn",
        "Becrypt",
        "Beeline",
        "BenQ",
        "Benesse",
        "Beneve",
        "Benten",
        "Bentley",
        "Bertoli",
        "Best Buy",
        "Beyond",
        "Bible-Pad",
        "Bigben",
        "Billion",
        "Billow",
        "Binatone",
        "BioRugged",
        "Bird",
        "Bitel",
        "Bitmore",
        "Bittium",
        "Bizringer",
        "Blabloo",
        "Black Bear",
        "BlackBerry",
        "Blackfox",
        "Blackshark",
        "Blacksonic",
        "Blackview",
        "Blaupunkt",
        "Blu",
        "Bluboo",
        "BlueTech",
        "Bluebird",
        "Bluedigit",
        "Bluedot",
        "Bluesky",
        "Bluslate",
        "Bmobility",
        "Booken",
        "Boost",
        "Borqs",
        "Bouygues Telecom",
        "BrailleNote",
        "Brandcode",
        "Brandt",
        "Brantel",
        "Brasiltec",
        "Bravis",
        "Bravva",
        "Brighton",
        "Brightstar",
        "British Telecom",
        "Brondi",
        "Brown",
        "Bubblegum",
        "Buddy Phone",
        "Bullitt Group",
        "Bunbungame",
        "Bundy Mobile",
        "Bush",
        "C&M",
        "C5 Mobile",
        "CALME",
        "CANAL-PLUS",
        "CBN Media",
        "CCC",
        "CCIT",
        "CEM Global",
        "CG Inspiring Life",
        "CG Mobile",
        "CGV (France)",
        "CHAINWAY",
        "CHCNAV",
        "CHN TELECOM",
        "CILICO",
        "CIMRL",
        "CIRKUIT PLANET (ESPANA)",
        "CJHelloVision",
        "CLEVER",
        "CLIO",
        "CMCC",
        "CONKER",
        "COOKIE",
        "COPAN",
        "CORN",
        "CP Plus",
        "CX Argentina",
        "CYX Group",
        "CZ Electronics",
        "Cablecolor",
        "Camelus",
        "Camfone",
        "Canal Digital",
        "Candi",
        "Candor",
        "Canguro",
        "Capstone",
        "Captiva",
        "Carbon Mobile",
        "CarePad",
        "Carrefour",
        "Casio",
        "Casper",
        "Cat",
        "Cathay",
        "Cavion",
        "Ceibal",
        "Celkon",
        "CellAllure",
        "Cell_C",
        "Cellacom",
        "Cellcom TV",
        "Cello",
        "Cellon",
        "Cellution",
        "Centric",
        "CenturyLink",
        "Chanbly",
        "Changhong",
        "Channel Master",
        "Chemist Warehouse",
        "Chenrui",
        "Cherry Mobile",
        "China Mobile",
        "China Network System (CNS)",
        "Chuwi",
        "Cipherlab",
        "Cisco",
        "Citycall",
        "Claresta",
        "Clarmin",
        "Classpro",
        "Clementoni",
        "Click",
        "ClickN Kids",
        "Clickonica Exclusive",
        "Clicktabds",
        "ClipSonic",
        "Cloud (TruConnect)",
        "CloudFone",
        "CloudMinds",
        "Clout",
        "Cobalt",
        "Coby",
        "Code",
        "Cogeco",
        "CoinComputers",
        "ColorsMobile",
        "Comio",
        "Compal",
        "Compaq",
        "Concord",
        "Condor",
        "Connectce",
        "Connex",
        "Connexion TV",
        "Conquest",
        "Contex",
        "Continental Edison",
        "Continential",
        "Contixo",
        "Coolpad",
        "Coppel",
        "Coppernic",
        "Covia",
        "Crema",
        "Cricket",
        "Cristor",
        "Croatian Telecom",
        "Crosscall",
        "Cspire",
        "Ctroniq",
        "Cubot",
        "Custom",
        "Cutepad",
        "Cyrus",
        "D-Tech",
        "DBM Maroc",
        "DCG-INSPIRATECH",
        "DEA Factory",
        "DEXP",
        "DEYI",
        "DGTEC",
        "DIADEM",
        "DIFRNCE",
        "DL",
        "DNA",
        "DO Mobile",
        "DSIC",
        "DTC products",
        "DTV (Thai)",
        "DUODUOGO",
        "Daehap",
        "Dahl Sweden",
        "Danew",
        "Dany",
        "Datalogic",
        "Datamini",
        "Datsun",
        "DayMark",
        "Ddm",
        "DeWALT",
        "Dell",
        "Delm",
        "Den Networks",
        "Denali",
        "Denka",
        "Denso Wave",
        "Denver Electronics",
        "DiDi (Japan)",
        "DiMora Mobile",
        "Dialog",
        "Dialog Blaze",
        "Diamond",
        "Dicle",
        "Digi",
        "DigiLand",
        "Digicel",
        "Digicom",
        "Digilite",
        "Diginnos",
        "Digital2",
        "DigitalStream",
        "Digitron",
        "Digix",
        "Digma",
        "Dinax",
        "Dingding",
        "Dintech",
        "Dish",
        "DishTV (IN)",
        "DishTV-NZ",
        "Disney",
        "Disney Frozen",
        "Disney Pixar",
        "Ditecma",
        "Ditigron",
        "Diva",
        "Dixon",
        "Docomo",
        "Dolamee",
        "Dom.ru",
        "Doogee",
        "Doopro",
        "Dopo",
        "Doppio",
        "Doro",
        "Dotpad",
        "Dragontouch",
        "Dreamax",
        "Dtac",
        "Dual",
        "Dunns",
        "Durabrand",
        "Duubee",
        "E-Boda",
        "E-TACHI",
        "E-Tel",
        "EBN",
        "ECS",
        "EKINOX",
        "EKO",
        "EL (Africa)",
        "ELO Touch",
        "EMCALI",
        "ENACOM",
        "ENDO Lighting",
        "ENIE",
        "ENTITY",
        "EONSmartBox",
        "EPIKONE",
        "ESI Enterprises",
        "EXCEED",
        "EXO S.A.",
        "Echo Mobiles",
        "EcoStar",
        "Edcon",
        "Edong",
        "Eigou",
        "Einstein",
        "Ekotek",
        "Eks Mobility",
        "Elecost",
        "Elecson",
        "Electroland Ghana",
        "Electroneum",
        "Element",
        "Elephone",
        "Elevate",
        "Elink",
        "ElliQ",
        "Elong Mobile",
        "Elsys",
        "Ematic",
        "Emdoor",
        "Emerson",
        "Emporia",
        "Emtec",
        "Energizer",
        "EnergySistem",
        "Engel",
        "Enspert",
        "Entel",
        "Entity",
        "Envizen",
        "Envizen Digital",
        "Epson",
        "Equator",
        "Ergo",
        "Erito",
        "Essential Products",
        "EssentielB",
        "Estar",
        "Estla",
        "Eten",
        "Etuline",
        "EuroLeague",
        "Euskaltel",
        "Evercoss",
        "Everex",
        "Everis",
        "Everpad",
        "Evertek",
        "Every",
        "Eviant",
        "Evolio",
        "Evolveo",
        "Evoo",
        "Excelvan",
        "Exertis",
        "Explay",
        "Express Gifts Limited",
        "Extrem",
        "EyePay",
        "F2 Mobile",
        "FANGOR",
        "FBC",
        "FCC Movil",
        "FELUX",
        "FFFSMARTLIFE",
        "FIREFLY MOBILE",
        "FLEX MOBILE",
        "FOXXD",
        "FPT Telecom",
        "FPT Trading",
        "FaceVsion",
        "Facime",
        "Fairphone",
        "Famous Fones",
        "Fantec",
        "FarEasTone",
        "Fero",
        "FieldBio",
        "Fiesta Duo",
        "Figgers",
        "Figi",
        "Figo",
        "Filih",
        "Finggo",
        "Firehawk",
        "FirstNationalBank",
        "Flash",
        "Flnet",
        "Flow",
        "Fluo",
        "Fly",
        "Fone Haus",
        "Fonos",
        "Ford",
        "Formuler",
        "Fossil",
        "Four Mobile",
        "Foxconn",
        "Foxtel",
        "Free",
        "Free Vision",
        "Freebit",
        "Freebox",
        "Freetel",
        "Fujitsu",
        "Funai Electric",
        "Fusion5",
        "Future Mobile Technology",
        "Fxtec",
        "G Y P NEW TREE SA",
        "G-Guard",
        "G-TOUCH",
        "G-Tab",
        "G-TiDE",
        "G-TiDE EXTREME",
        "G53",
        "G7 Mobiles",
        "GC(TECH)",
        "GD Classbook",
        "GENESIS",
        "GEOFOX",
        "GFive",
        "GHIA KIDS",
        "GIGI",
        "GIRASOLE",
        "GP-electronic",
        "GREATASIA",
        "GRID Communications (SG)",
        "GSmart",
        "Galactic",
        "Galapad",
        "Galax",
        "Galexia",
        "Garad",
        "Garmin",
        "Gasei S.A.",
        "Geanee",
        "Geant",
        "Gear Mobile",
        "Geecoo",
        "Gen2Wave",
        "General Dynamics",
        "General Mobile",
        "GeneralMobile",
        "Geniatech",
        "Geniora",
        "Geo (GeoTechVision)",
        "Gesellschaft f뿯½r SMK mBH",
        "Get",
        "Getac",
        "Getnord",
        "Ghia",
        "Gigabyte",
        "Gigaset",
        "Gini",
        "Ginzzu",
        "Gionee",
        "Globe Phoenix",
        "Globe Telecom",
        "Glocalme",
        "Glofiish",
        "Go Mobile",
        "GoClever",
        "Gobox",
        "Gol Mobile",
        "Goldmaster",
        "Goldtech",
        "Gome",
        "Gonna",
        "Goo",
        "Google",
        "Gplus",
        "Gradiente",
        "Greatwall",
        "Greentel",
        "Grolier",
        "Grundig",
        "Gryphon",
        "Gtel",
        "Guess",
        "Guophone",
        "HANYEAL",
        "HDC S.A.",
        "HDD SAT",
        "HKC",
        "HKT",
        "HMR NETWORKS",
        "HOMTOM",
        "HP",
        "HRSolutions",
        "HTC",
        "HUAVI",
        "HYUNDAI_MAESTRO",
        "Hackers",
        "Haehne",
        "Hafury",
        "Haier",
        "HaloBop (ShenZhen)",
        "Hamic",
        "Hamlet",
        "Handheld Group",
        "HannSpree",
        "Harman TV",
        "Harris",
        "Hatch",
        "Hathway",
        "Haus",
        "Helio",
        "Hercls",
        "Hero",
        "HexaByte",
        "Hezire",
        "Hi TFG",
        "Hi-online",
        "HiMedia",
        "HighScreen",
        "High_Q",
        "Hihi",
        "Hiking",
        "Himax",
        "Hipstreet",
        "Hisense",
        "Hitachi",
        "Hiya",
        "Hllo",
        "Hoffmann",
        "Hometech",
        "Hon Hai Precision Industry Co., Ltd.",
        "Honda",
        "Honeywell",
        "Hoozo",
        "Hot Pepper",
        "Hotwav",
        "How",
        "Huangmi",
        "Huawei",
        "Hublot",
        "HumaxDigital",
        "Hurricane",
        "Huskee",
        "Hykker",
        "Hytera",
        "Hyundai",
        "Hyve",
        "I-Scream",
        "ICL-KME CS OJSC",
        "ICOM",
        "IDC",
        "IDEA",
        "IDONDRDO",
        "IDspire",
        "IKALL",
        "IMO(In My Opinion)",
        "INOI",
        "INOVALLEY",
        "INQ Mobile",
        "INSYS",
        "ION ELECTRONICS",
        "IPRODA",
        "IQ Touch",
        "ITOS",
        "IUNI",
        "IUSA",
        "IVA Mobile",
        "IView",
        "IWRIST",
        "IZZI Telecom",
        "Ice Phone",
        "Icon",
        "IguanaPad",
        "Ikimobile",
        "Ikon",
        "IkuMobile",
        "Ilike",
        "ImageMobile",
        "Imi Tech",
        "Impecca",
        "Impression",
        "Inco",
        "IndiHome",
        "Inet-Tablet",
        "Infinity",
        "Infinix",
        "Infocus",
        "Ingenico",
        "Inhon",
        "Innjoo",
        "Innopia",
        "Inovacel",
        "Insignia",
        "Inspire Mobile",
        "Inspur",
        "Intel",
        "Intelbras",
        "Intenso",
        "Intermec",
        "Intex",
        "Invens",
        "Inverse Net",
        "Ipro",
        "Iproda",
        "Irbis",
        "Iris",
        "Isafe",
        "Itel",
        "Itworks",
        "J:COM",
        "JAY-TECH",
        "JLab",
        "JP Sacouto",
        "JVC",
        "JVL (Australia)",
        "JabrBox",
        "Janam",
        "Japan Digital Serve",
        "JapanTaxi",
        "Jenesis",
        "Jesy",
        "Jide",
        "Jimi",
        "Jimo",
        "Jinga",
        "Jivi",
        "Jooyon",
        "Juniper Systems",
        "Just5",
        "Jyonetsu Kakaku",
        "K-LEADTONE",
        "K-Lite,",
        "K-Touch",
        "KAAN",
        "KANSELIR",
        "KAZAM",
        "KCCL",
        "KCTV",
        "KD Interactive",
        "KDDI",
        "KEMPLER STRAUSS",
        "KISA phone",
        "KNC (LK)",
        "KONKA",
        "KOOLNEE",
        "KOOOK",
        "KRIP",
        "KT Tech",
        "KTV",
        "KZG (Ke Zhi Guang)",
        "Kaicom",
        "Kalley",
        "Kanji",
        "KaonMedia",
        "Kapsys",
        "Karbonn",
        "Karvy",
        "Kbro",
        "Keian",
        "Kelyx",
        "Kempler Strauss",
        "Kenbo",
        "Kennex",
        "Kenwood",
        "Kenxinda",
        "Ketablet",
        "Kiano",
        "Kids_and_Us",
        "Kimfly",
        "Kinetic",
        "Kingcomm",
        "Kinstone",
        "Kioto",
        "Kiowa",
        "Kivi",
        "Klipad",
        "Kobo",
        "Kodak",
        "Kogan",
        "Komu",
        "Konrow",
        "Krik Krak",
        "Krono",
        "Kruger&Matz",
        "Kubo",
        "Kudae",
        "Kult",
        "Kurio",
        "Kyocera",
        "Kyowon",
        "Kzen",
        "LBQ (UK)",
        "LEOMO",
        "LEVEL TV",
        "LEYO",
        "LGE",
        "LGU+",
        "LIAONING YIYATONG",
        "LIFE Digital",
        "LINNEX",
        "LINSAY",
        "LLA",
        "LOOQS",
        "LP (TN)",
        "LT Electronics",
        "LUMUS",
        "LUVO",
        "LUXO",
        "LUXYA",
        "LW",
        "Laiq",
        "Lamborghini",
        "Land Rover",
        "Landbyte",
        "Lanix",
        "Lark",
        "Laser",
        "Lava",
        "Lazer",
        "Le",
        "Le Pan",
        "LeBest",
        "LeTV",
        "Leader Phone",
        "Leagoo",
        "Lechpol",
        "Leeco",
        "Lenovo",
        "Leotec",
        "Lephone",
        "Lesia",
        "Lexia Mobile",
        "Lexibook",
        "Lgcns",
        "Libre",
        "Life Stick",
        "Life mobile",
        "LifeWatch",
        "Lilus",
        "Lin",
        "LinkNet",
        "Linsay",
        "Lisheng",
        "Listo",
        "LiteTEL",
        "Logic Instrument",
        "Logic Mobility",
        "Logicom",
        "Logitech",
        "Louis Vuitton",
        "Lucentel",
        "Lumigon",
        "Lumitel",
        "Lyf",
        "M-Horse",
        "M-tech",
        "M3 Mobile",
        "M4tel",
        "MAG",
        "MASTERTECH",
        "MAXX",
        "MAZE",
        "MDC Store",
        "MG Series",
        "MG series",
        "MINIX",
        "MIRAY",
        "MITSUSHIBA",
        "MJS",
        "MLAB",
        "MLS Innovation",
        "MNC NOW",
        "MOBO",
        "MOBULAA",
        "MOVI",
        "MOVIC",
        "MOVISUN",
        "MPman",
        "MSI",
        "MSota",
        "MTC",
        "MTN Group",
        "MTN-E70",
        "MTR (MY)",
        "MTS (RU)",
        "MTT",
        "MTab",
        "MU (TH)",
        "Mach Speed",
        "MachSpeed (Apollo Brands)",
        "Mad Catz",
        "Mafe",
        "MagentaTV",
        "Majestic",
        "Making Life Simple",
        "Malata",
        "Mango",
        "Manta",
        "Mantra",
        "MarQ",
        "Mara Phones",
        "Marshall",
        "Marvie",
        "Mascom",
        "Masstel",
        "Master-G",
        "MauritiusTelcom",
        "Maxcom",
        "Maxfone",
        "Maximus",
        "Maxis",
        "Maxon",
        "Maxpac",
        "Maxtron",
        "Maxvi",
        "Maxwest",
        "Maze_speed",
        "MeanIT",
        "Meberry",
        "Mecer",
        "Mecool",
        "Mediabox",
        "Mediacom",
        "Medion",
        "MegaFon",
        "Megahouse",
        "Meiigoo",
        "Meitu",
        "Meizu",
        "Memorex",
        "Mgt electric",
        "MiTAC",
        "Micromax",
        "Microtech",
        "Mightier",
        "Migu",
        "MiiA",
        "Mikona",
        "Mint",
        "Mintt",
        "Mio Tab",
        "Mione",
        "Miophone",
        "Mirage",
        "Mito",
        "Mobell",
        "MobiIoT",
        "MobiOcean",
        "Mobicell",
        "MobiiStar",
        "Mobile Initiative",
        "MobileDemand",
        "MobileTeleSystem",
        "Mobily",
        "Mobiola",
        "Mobistel",
        "Mobiwire",
        "Mobvoi",
        "Mode1",
        "Modecom",
        "Mohu",
        "Mola TV",
        "Molvu",
        "Mondial",
        "Monster",
        "Monsterpad",
        "Montblanc",
        "Morep",
        "Mosambee",
        "Most Computers",
        "Motorola",
        "Motorola Solutions",
        "Movado",
        "Moveby",
        "Movic",
        "Moviltelco Trade",
        "Moviltelco Trade S.L",
        "Movistar",
        "Movitel",
        "Moxee Technologies",
        "MozaTab",
        "Mpgio",
        "Mpman",
        "Multilaser",
        "My",
        "My Go",
        "MyBox",
        "MyFon",
        "MyPhone (PL)",
        "Myphone",
        "Myria",
        "Myros",
        "Mytron",
        "NASCO",
        "NAVA",
        "NAXA",
        "NCTC",
        "NEC",
        "NEO",
        "NEONIQ",
        "NESO",
        "NETGREEN",
        "NEWSUN",
        "NGM Italia SRL",
        "NOA Mobile",
        "NOGA",
        "NVIDIA",
        "NYX Mobile",
        "Nabi",
        "Nanho",
        "Nano",
        "NanoTech",
        "Naomi Phone",
        "Natcom",
        "Nautilus",
        "Navcity",
        "Navitel",
        "Navon",
        "Naxa",
        "Ncredible",
        "Nebula",
        "Necnon",
        "Neffos",
        "Nelson Mandela",
        "Neostra",
        "Net+",
        "Netgear",
        "Netmak",
        "Neusoft",
        "New Balance",
        "Newings",
        "Newland",
        "Newsday",
        "Nexian",
        "Next Learning",
        "Next Technologies",
        "Nextbase",
        "Nextbit",
        "Nextbook",
        "Nextel",
        "Nextgear",
        "Nikon",
        "Nixon",
        "Njoy",
        "Nobby",
        "Nobis",
        "Noblex",
        "Nokia",
        "Nomi",
        "Nomu",
        "NorthTech",
        "Nous",
        "Novinsun",
        "Now E",
        "Nowtha",
        "NuAns",
        "Nubia",
        "Nubio_Lite",
        "Nuu",
        "Nuvision",
        "O'NICE",
        "OASYS",
        "OBOX",
        "ODYS",
        "OK (Mediamark)",
        "OKWU",
        "ONDA TLC",
        "ONYX",
        "ORBYS",
        "ORCA",
        "OTHO",
        "OTK",
        "OTOT",
        "OTTO",
        "OWXMobile",
        "OYYU",
        "Oale",
        "Obi",
        "Oceusnetworks",
        "Odotpad",
        "Odys",
        "Oioo",
        "Olive Oil",
        "Olivetti",
        "Olla",
        "Ollee",
        "OneClick",
        "OneLern",
        "OnePlus",
        "Onix",
        "Onkyo",
        "Onn (Walmart)",
        "Ooredoo",
        "Opay",
        "OpelMobile",
        "OpenPeak",
        "Ophone",
        "Oppo",
        "Opticon",
        "Oraimo",
        "Orange",
        "Orange TV",
        "Orbic",
        "Orient",
        "Oukitel",
        "Overmax",
        "OwnMobile",
        "Oysters",
        "PAPAGO",
        "PAX (CN)",
        "PC Smart",
        "PCBOX",
        "PCD Argentina",
        "PILOT",
        "PLDT",
        "POC",
        "POCO",
        "POPTEL",
        "PORTFOLIO",
        "PROGRACE",
        "PS_Mobile",
        "PT mobile",
        "Packard Bell",
        "PadBook",
        "Palm",
        "Panasonic",
        "Panodic",
        "Pantech",
        "Parrot Mobile",
        "Partner",
        "Pastigio",
        "Pavapro",
        "Pegatron",
        "Pendo",
        "Peninsula",
        "Penta",
        "Performance",
        "Perseo TV",
        "Philco",
        "Philips",
        "Phoenix",
        "Phone Max",
        "Pioneer",
        "Pitney Bowes",
        "Pixela",
        "Pixus",
        "Plaisio",
        "Planet Computers",
        "PlayPoland",
        "Plum",
        "Plus4",
        "Plusone",
        "Pluzz",
        "Point Mobile",
        "Point of view",
        "Pokini",
        "Polar",
        "Polaris",
        "Polaroid",
        "Polestar",
        "Polytron",
        "Porsche",
        "Positivo",
        "Positivo BGH",
        "Powerway",
        "Precision Biometric",
        "Premier",
        "Premio",
        "Prestige",
        "Prestigio",
        "Prime",
        "Primux",
        "Prince Mobile",
        "Prism",
        "Pritom",
        "Prixton",
        "Prodigi Connect12",
        "Professional Mobile",
        "Proline",
        "Proscan",
        "Protab",
        "Punos",
        "QBell",
        "QFX USA",
        "QLA",
        "QMobile",
        "QOCA",
        "QOOQ",
        "QPS Digital Electronics",
        "QTab",
        "QUBO",
        "Qilive",
        "Qoobex",
        "Qpad",
        "Qsmart",
        "Qtouch",
        "Quanta",
        "Quantum",
        "Quatro",
        "Quickline",
        "RAVOZ",
        "RCA",
        "REACH",
        "RED",
        "RIVERSONG",
        "ROKiT",
        "RT Project",
        "Radger",
        "Rainbow",
        "Rakuten",
        "Ratel",
        "Rayan",
        "Raylandz",
        "Razer",
        "Realme",
        "Realtek",
        "Realtime",
        "Rectron",
        "Red Mobile",
        "Red-X",
        "Redmi",
        "Redway",
        "Reeder",
        "Rego",
        "Reliance",
        "Remdun",
        "Reveal 16i",
        "Revko",
        "Revo",
        "Revtel",
        "Rinno",
        "Rixun",
        "RockTek",
        "Rockcel",
        "Royaltek",
        "Royqueen",
        "RuggON",
        "Ruggear",
        "Ruio",
        "Rumie",
        "Runbo",
        "S Vision",
        "S&T Global",
        "S-tell",
        "SAGI",
        "SAIET",
        "SAKAISIO",
        "SARL WISE TECHNOLOGIE",
        "SBET",
        "SCHNEIDER",
        "SCIENTIA",
        "SED Wireless",
        "SELECLINE",
        "SEMP TCL",
        "SERVO",
        "SEWOO",
        "SFR",
        "SFR.fr",
        "SGINO",
        "SHIFT",
        "SHINON",
        "SIAFU",
        "SK Broadband",
        "SK Telesys",
        "SMB Gadgets",
        "SMT_LW",
        "SMT_SN",
        "SMT_TSC",
        "SOLO",
        "SORIANA",
        "SOSMART",
        "SPC Mobile",
        "SPC Universe",
        "SSB PHONES",
        "STF Mobile",
        "STG Telecom",
        "STIP",
        "STK(Santok)",
        "SUPERSONIC",
        "SYLVANIA",
        "Safaricom",
        "Sagemcom",
        "Saltillo",
        "Samsung",
        "Samtech",
        "Sanaeko",
        "Sankey",
        "Sansei",
        "Sansui",
        "Sansui TV",
        "Sanyo",
        "Sapphire",
        "Sasktel",
        "Sceptre",
        "Schok",
        "Scope",
        "Sea Mobile",
        "Seatel",
        "SecQre",
        "Secureye",
        "Seeken",
        "Seemahale Telecoms",
        "Seiki",
        "Selectron",
        "Selfix",
        "Selvas",
        "Senseit",
        "Senwa",
        "Servicom IT",
        "Seuic",
        "Sharp",
        "Shelby",
        "Shenzhen Jiuzhou",
        "Shenzhen SEI Robotics",
        "Shuttle",
        "SiAL",
        "Sico",
        "Sico SmartPhone",
        "Sigma Mobile",
        "Silent Circle",
        "Silver line",
        "Simbans",
        "SimiMobile",
        "Singer",
        "Singtech",
        "Sintel",
        "Siragon",
        "Sirin",
        "Sky (CH)",
        "Sky Devices",
        "SkyLife",
        "Skyview",
        "Skyworth",
        "SledovaniTV",
        "Smadl",
        "Smailo",
        "Smart",
        "Smart (BD)",
        "Smart-Tech TV",
        "SmartPad",
        "Smartab",
        "Smartbook",
        "Smartec",
        "Smartek",
        "Smartex",
        "Smartfren",
        "Smartron",
        "Smile",
        "Smooth",
        "Snopow",
        "So ! Generation",
        "Soda",
        "Solone",
        "Sonimtech",
        "Soniq",
        "Sony",
        "Sony Ericsson",
        "SonyAudio",
        "Sophix_Digix",
        "Sourcing Creation",
        "Southern Telecom",
        "SoyMomo",
        "Spark",
        "SpectraPrecision",
        "Spectralink",
        "Speedmind",
        "Spice",
        "Sprint",
        "StarHub",
        "StarMobile",
        "Starlight",
        "Stofa",
        "Storex",
        "Strawberry",
        "Stream",
        "Sts-tottori",
        "Stylo",
        "Stylos",
        "Stylus",
        "Sugar",
        "Sumitomo Electric Industries",
        "Sumitomo Electric Networks",
        "Sunbio",
        "Sunny",
        "Sunstech",
        "Supertab",
        "Suponic",
        "Supraim",
        "Surgephone",
        "Surtab",
        "Suunto",
        "Sweam",
        "Swipe",
        "SwissMobility",
        "Swisstone",
        "Switel",
        "Syinix",
        "Symphony",
        "T-Mobile",
        "TA71CA5_JP",
        "TAG Heuer",
        "TAG-DC",
        "TAG-TECH",
        "TAGITAL",
        "TASKPHONE",
        "TBC (TW)",
        "TCL",
        "TCT (Alcatel)",
        "TDS",
        "TECHNOLOGIA Y CRATIVIDAD",
        "TERRA",
        "TES (Touch Embedded Solutions)",
        "TESPRO",
        "TG&Co.",
        "THEHAM",
        "THL",
        "THOMSON_KODAK",
        "THTF",
        "TIM",
        "TJC",
        "TM Cell",
        "TMAX",
        "TO21COMMS",
        "TONE",
        "TOPELOTEK",
        "TOSCIDO",
        "TOUCHSMART",
        "TPS",
        "TREQ",
        "TSUNAMi",
        "TTS-group",
        "TUFEN",
        "TUFF",
        "TUNTUN English",
        "TUPAD",
        "TVB",
        "TVUp",
        "TWOE",
        "TWZ Corporation PLC",
        "TabletKiosk",
        "Tabletop",
        "TaiwanMobile",
        "Takara",
        "Talius",
        "Tambo",
        "Tanoshi",
        "TataSky",
        "TazTag",
        "Tech 4u",
        "Technicolor",
        "Technocrat",
        "Techpad",
        "Techsonic",
        "Teclast",
        "Tecno",
        "Teeno",
        "Teesso",
        "TekSavvy",
        "Teknosa",
        "Tekwind",
        "Telcel",
        "Tele2",
        "Telecable",
        "Teleepoch",
        "Telefunken",
        "Telegenic",
        "Telego",
        "Telelynx",
        "Telemor",
        "Telenet",
        "Telenor",
        "Telkom",
        "Telkom Indonesia",
        "TellyTablet",
        "Telma",
        "TeloSystems",
        "Telus",
        "Teracube",
        "Tesco",
        "Tesla",
        "Tetratab",
        "Thinpad",
        "Thomson",
        "Thuraya",
        "TiVo Stream 4K",
        "Tigers",
        "Tiitan",
        "Time2",
        "Timmy",
        "Timor Telecom",
        "Timovi",
        "Tinhvan",
        "Tinmo",
        "Tinp",
        "Tiwell",
        "Tobii DynaVox",
        "Tokio",
        "TomStar",
        "Tonino Lamborghini",
        "Toshiba",
        "Toshiba Tec Corporation",
        "Touch plus",
        "Touchmate",
        "Toughshield",
        "Transvision",
        "Trekstor",
        "Trend Mobile",
        "Trend Solar",
        "Trevi",
        "TriaPlay",
        "Trifone",
        "Trimble Navigation",
        "Trio",
        "True",
        "TuCEL",
        "Tunisie Telecom",
        "Turbo-X",
        "Turbokids",
        "Turbonet",
        "Turbopad",
        "Turk Telekom",
        "UKA-Dream",
        "ULCOOL",
        "UNILORIN",
        "UNITED TV",
        "UNOWHY",
        "USA111",
        "USP (The University of the South Pacific)",
        "UTVbox",
        "Ubiquiti",
        "Ulefone",
        "Umax",
        "Umidigi",
        "Umiio",
        "Umix",
        "Umx(Ultimate Mobile Experience)",
        "Uneone",
        "Unifi-TV",
        "Unifone",
        "Unihertz",
        "Unionaire",
        "Unistrong",
        "Unitech",
        "United Group",
        "Unnecto",
        "Unnion Technologies",
        "Unonu",
        "Uphone",
        "Upserve",
        "Urovo",
        "Usha Shriram",
        "Utopia",
        "V2COM",
        "V7",
        "VAIO",
        "VALIFONE",
        "VALTECH",
        "VANTEC",
        "VBox",
        "VENSTAR",
        "VIBE Z",
        "VNPT Technology",
        "VOLFEN",
        "VOLIA",
        "VORCOM",
        "VSN",
        "VT",
        "VUCATIMES",
        "Valo Innovations",
        "Vankyo",
        "Vava",
        "Vaxcare",
        "Vectra",
        "Vega",
        "Veidoo",
        "Venso",
        "Venturer",
        "Venus",
        "VerD",
        "Verizon",
        "Verizon Wireless",
        "Vernee",
        "Verssed",
        "Vertex",
        "Vertu",
        "Verykool",
        "Vestel",
        "Vexia",
        "VfonX",
        "Vgo Tel",
        "Victurio",
        "Vida",
        "Viettel",
        "ViewSonic",
        "Virzo",
        "Vision Technology",
        "Visiontech",
        "Visiontouch",
        "Visual Land",
        "Vitsmo",
        "Viumee",
        "Vivax",
        "Vivo",
        "Viwa",
        "Vizio",
        "Vizmo",
        "Vizualogic",
        "Vkworld",
        "Vmobile",
        "Vodafone",
        "Volt Mobile",
        "Vonino",
        "Voo",
        "Vorago",
        "Vortex",
        "Voto",
        "Vsmart",
        "Vsun",
        "Vu Televisions",
        "Vue Micro",
        "Vulcan",
        "W&O",
        "W.e.",
        "WIIGO",
        "WILL (JP)",
        "Wacom",
        "Waf",
        "Walton",
        "Wansa",
        "Warner Bros",
        "Wave 8",
        "Wave 8 Red Nougat",
        "We (BD)",
        "WeTek",
        "Webfleet Solutions",
        "Weimei",
        "Welgate",
        "Welwitcha",
        "Wenu",
        "Westgate",
        "Westinghouse",
        "Wexler",
        "Wibox",
        "Wieppo",
        "Wigor",
        "Wiko",
        "Wileyfox",
        "Win (VE)",
        "Winds Mobile",
        "Wings",
        "Wink",
        "Winmax",
        "Winnovo",
        "Wintec",
        "Wintouch",
        "Wise-Tech",
        "Wiseasy",
        "Wishtel",
        "Wistron",
        "Witooth",
        "Wizphone",
        "Wizz",
        "Wolki",
        "Woongjin",
        "Wopad",
        "Wowi",
        "Woxter",
        "X-Age",
        "X-PREMIUM",
        "X-TEK",
        "X-TIGI",
        "X-View",
        "XGIMI",
        "XL Axiata",
        "XTRATECH_IGUANAPAD",
        "Xcell",
        "Xgody",
        "Xiaomi",
        "Xolo",
        "Xplore Technologies",
        "Xstar",
        "Xtratech",
        "Xwave",
        "YELLYOUTH",
        "YOTOPT",
        "YSFEN",
        "YU",
        "YUNTAB",
        "Yandex",
        "Yekani",
        "Yes",
        "YesTeL",
        "Yezz",
        "Yokis",
        "Yota Devices",
        "Youfone",
        "Yuho",
        "Yumpingo",
        "ZENTALITY",
        "ZLINE",
        "ZMBIZI",
        "ZOOMME",
        "ZOOMSMART",
        "ZTE",
        "ZUKU",
        "Zaith",
        "Zatec",
        "Zebex",
        "Zebra",
        "Zeki",
        "Zelumobile",
        "Zen",
        "Zettaly",
        "Zexelon",
        "Zilo",
        "Ziox",
        "Zoji",
        "Zonda",
        "Zong 4G",
        "Zonko",
        "Zoom",
        "Zopo",
        "Zpad",
        "Zuk",
        "Zuum",
        "afriphone",
        "alter",
        "aoson",
        "beafon",
        "benco",
        "boxchip",
        "bq",
        "carrozzeria",
        "d.light",
        "dazen",
        "duraMOBI",
        "eBox",
        "eSTREAM 4K",
        "eTalk",
        "ecom",
        "efioo",
        "halotel",
        "i-Buddie",
        "i-Mobile",
        "iBRIT",
        "iBall",
        "iBao",
        "iCraig",
        "iData",
        "iDea USA",
        "iDeaUSA",
        "iDevice",
        "iFit",
        "iGet",
        "iHunt",
        "iLa Mobile",
        "iLife",
        "iMuz",
        "iNFONE",
        "iNO Mobile",
        "iNanny",
        "iNew",
        "iPlus",
        "iQandT",
        "iQual",
        "iRainbow",
        "iReplace",
        "iRiver",
        "iRulu",
        "iSWAG",
        "iTab XPLUS",
        "iTree",
        "iVOOMi",
        "iWaylink",
        "iYOU",
        "imose",
        "indigi",
        "intelkom",
        "ioutdoor",
        "koobee",
        "mytel",
        "neocore",
        "neutab",
        "newsan",
        "noDROPOUT",
        "novo",
        "pendo",
        "robi",
        "sencor",
        "sf-express",
        "sugar_aums",
        "teXet",
        "techBITE",
        "tecmobile",
        "truevisions",
        "truvii",
        "ucall",
        "unitel",
        "vatenick",
        "videocon",
        "xTouch",
        "zyrex"
    ]
    return random.choice(brands_list)




def generate_random_companies():
    return return_brand()



